### ISSUE TITLE
Custom deprecated but no way provided to present from SwiftUI

### ISSUE THREAD

**Issue by derikflanary** [plaid/plaid-link-ios#34]
I'm seeing this warning now on the latest release. 
"'custom' is deprecated: Presenting Link with modalPresentationStyle .overFullScreen or .fullScreen is no longer supported. You may experience UI issues if you present Link using those modalPresentationStyles."

However this is the main way you provide to present Plaid is SwiftUI. How then should we present it. I can't get `.viewController` to work.

**Comment by dtroupe-plaid** [comment]
Hi @derikflanary thanks for flagging. 

The deprecation is a warning about presenting Link using `.overFullScreen` or `.fullScreen` [UIModalPresentationStyle](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle). As long as you're not using either of those styles there is nothing to be concerned about. 

Let me know if you have additional questions.

**Comment by 3a4oT** [comment]
Hey, I have the same question. If it's okay to have `custom`,  then it shouldn't be deprecated and should produce a warning.

**Comment by dtroupe-plaid** [comment]
I'll remove the deprecation in the next release.

**Comment by dtroupe-plaid** [comment]
This deprecation was removed in [5.4.0](https://github.com/plaid/plaid-link-ios/releases/tag/5.4.0)
