### ISSUE TITLE
Missing purpose for User ID usage in PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by itskoBits** [plaid/plaid-link-ios#38]
### A detailed description of the steps to reproduce the issue
I see a `PrivacyInfo.xcprivacy` file was recently added to this repository to help app developers to understand the API use and data-collection practices of your SDK. However there is some info missing in the `PrivacyInfo.xcprivacy` file. The `NSPrivacyCollectedDataTypePurposes` for `NSPrivacyCollectedDataTypeUserID` seems to be an empty array. 

This can also be seen when generating a privacy report using the `LinkKit` SDK.
![image](https://github.com/plaid/plaid-link-ios/assets/4847686/e51dd917-6abd-441d-b312-138eab0d527c)

### What you expected to see?
I expect that a reason for collection the data will be entered in the `PrivacyInfo.xcprivacy` file as described in this document by Apple - https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests.

**Comment by dtroupe-plaid** [comment]
@itskoBits thanks for reporting. I will resolve this in the next SDK release.

**Comment by dtroupe-plaid** [comment]
This was added in `4.7.7` and `5.5.0` which were released today. I'm going to close this issue, please let me know if there are any issues.
