### ISSUE TITLE
Vulnerability in LinkKit (5.6.0) in Plaid-link-ios

### ISSUE THREAD

**Issue by MuhammadMazhar313** [plaid/plaid-link-ios#45]
We have identified a vulnerability in the versions of LinkKit (5.6.0) used in Plaid-link-ios.  Plaid sandbox URL is being exposed in Linkkit. This issue was detected using the MobSF security analysis tool.

Details:

LinkKit version: 5.6.0
Affected Component: Plaid-link-ios
Detection Tool: MobSF

**Comment by dtroupe-plaid** [comment]
Hi @MuhammadMazhar313, 

Please report any suspected vulnerabilities using our official channel: https://hackerone.com/plaid
